sudo: required

services:
  - docker

before_install:
  - docker image build -t wailm/docker-react -f Dockerfile.dev .

script:
  - docker container run --rm wailm/docker-react:latest npm test -- --ci --watchAll=false
