version: '3.9'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - frontend-modules:/home/app/node_modules
      - .:/home/app
volumes:
  frontend-modules: